### PR TITLE
Fix for https://github.com/AppThreat/cdxgen/issues/148

### PR DESCRIPTION
**Pull request by bobflannigon**
https://github.com/AppThreat/cdxgen/issues/148

### CODE REVIEW

**Comment by jkowalleck** [comment]
@bobflannigon  what is this PR all about?

**Review by jkowalleck — CHANGES_REQUESTED** [review]
to much breaking changes, to muck for one PR.
please split this up in individual feature-based pull requests.

**Comment by jkowalleck** [comment]
@bobflannigon i guess you pullrequested to the prong repository.
this is not https://github.com/AppThreat/cdxgen

**Comment by bobflannigon** [comment]
Yeah I think so, this one seems so diverged, but I couldn't find 'master' anywhere!  I haven't even pushed my change up yet, I think I need permission to do so? I just want to make a small change on your master branch because CDXGEN_TIMEOUT_MS doesn't work and so it times-out on my repo because it takes longer than 10 minutes (pretty odd/arbitrary default).  

Perhaps you could point me at the right repository that I can change?

**Comment by jkowalleck** [comment]
this project is not cdxgen but a totally different one. there is no such CDXGEN_TIMEOUT_MS in this project.

the correct repo seams to be https://github.com/AppThreat/cdxgen

**Comment by bobflannigon** [comment]
Yeah, okay, apologies.  I think I got sent here from there.

**Pull request closed without merging**
