### PR TITLE
v4.0

### LINKED ISSUE #86: Support for {yarn,npm} workspaces
We use a mono repo with yarn workspaces. I've tried running `cyclonedx-bom` at the repo root and in individual projects but it doesn't detect any packages.
Cli Error:

> There are no components in the BOM. The project may not contain dependencies or node_modules does not exist. Executing `npm install` prior to CycloneDX may solve the issue.

Testing with a single project repository works as expected.

Is this supported?

### LINKED ISSUE #113: Set MetaData Component from Outside
It would be helpful when I can set the name and version of the metaData component from outside.

### LINKED ISSUE #117: REgression in version 2.0.2
I observe a regression in the version 2.0.2, this happens:

cyclonedx-bom -h
/usr/lib/node_modules/@cyclonedx/bom/node_modules/ssri/index.js:25
const ssriOpts = (opts = {}) => ({ ...defaultOpts, ...opts })
                                   ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/@cyclonedx/bom/model/HashList.js:19:14)

Note : the program behaves normally in version 2.0.1

### LINKED ISSUE #180: [YARN] use only top-level .lock file to avoid inflating BOM with uninstalled package versions
When I run cyclonedx-bom on a yarn-managed project with a yarn.lock file, the BOM contains lots of package versions that aren't installed, as yarn resolves into a single version. Based on a seemingly similar issue that turned up in the context of the syft BOM scanner, https://github.com/anchore/syft/issues/431, this might be due to not ignoring nested .lock files.

### LINKED ISSUE #182: Missed dependencies due to incorrect extraneous attribute assigned by `read-installed`
When trying cyclonedx-bom both with and without `-d` parameter in one of our internal big repos in my workplace, I found that this script missed many dependencies. This results in missing a lot of vulnerabilities when processing the bom file with tools like OWASP Dependency Track.

After some debugging, I found that the root cause is some dependencies are marked as `extraneous` by `read-installed`, even tough the dependency is not in `devDependencies`. Even when I run the script with `-d` parameter, many `devDependencies` are also missed because the `extraneous` attributes are set to true.

This is problematic because this script relies on `extraneous` attribute to include/exclude the package:

```javascript
  createComponent(pkg, list, lockfile, isRootPkg = false) {
    //read-installed with default options marks devDependencies as extraneous
    //if a package is marked as extraneous, do not include it as a component
    if(pkg.extraneous) return;
    ...
  }
```

I haven't investigated why `read-installed` incorrectly set the `extraneous` attributes of some dependencies but this library is actually not maintained anymore since 6 years ago. The repo is already archived with some unresolved issues. For the continuity of this project, I suggest you to find another way to read installed dependencies.

For workaround, can we create an option param to bypass `if(pkg.extraneous) return;`?

### LINKED ISSUE #198: transitive dev-dependency not properly detected as dev-dependency
Hello. 
I am using Version 3.1.1 of the package and found a error in processing the dev dependencies that leads to wrong results.
Using here the example of the package netmask.
Which is a indirect child dependency of inline-css as you can see in package-tree.txt.
And included inside devDependencies of our package.json.

Yet it appears inside of the generated bom file.

[package-tree.txt](https://github.com/CycloneDX/cyclonedx-node-module/files/7596194/package-tree.txt)

[bom.txt](https://github.com/CycloneDX/cyclonedx-node-module/files/7596205/bom.txt)

Another example are all items with:  <group>@types</group>
Which are typescript typings and all listed under devDependencies of package.json.

### LINKED ISSUE #215: drop `read-installed`
@DarthHater reported `read-installed` being end of live.
He suggested to switch to [`@npmcli/arborist`](https://www.npmjs.com/package/@npmcli/arborist).

`read-installed` also semas to be causing a lot of issues. see other/related/linked issues.

----

acc/crit: 
- have a deeper/proper test case for it - that fails with the old lib, - have it pass with new lib
  there are several existing issues that are reporting issues.

definition of done:
- [ ] implement a solution
- [ ] announce this dependency change in the CHANGELOG/HISTORY -- category  "internal & maintenance"
- [ ] release a alpha/preview version and ask existing issue authors to test it 
- [ ] merge implementation to master 
- [ ] release as v3.x 

----

this fix was originally planned for the next upcoming [milestone **v4**](https://github.com/CycloneDX/cyclonedx-node-module/milestone/2)
As implementation and behaviorql changes are seen as breaking changes.

### LINKED ISSUE #219: use proper value assertions in constructors
most constructors assign object properties, while the properties themself have public setters which  may throw `RangeError`/`TypeError`/etc
this means: the setters are **not** asserting the correct value type and value domain.

this needs to be fixed, the correct validation methods need to be used.

**ATTENTION**
This is considered a breaking change, since new error throws would be introduced.

### LINKED ISSUE #220: DOCS: add typehints
current implementation is untyped undocumented javascript

as a user of this library i want type docs, so that i know expected parameter types.
as a user of this library i want type docs, so that i know possible throws.
as a user of this library i want type docs, so that i know possible return types.
as a user of this library i want type docs, so that tools/IDE assistance is improved.

options: 
* rewrite the whole thing in typescript.
* add [jsdoc](https://jsdoc.app/) to methods, properties, classes,
* add type definition files (`*.d.ts`) to the project 

enforce typehints via eslint rules: https://github.com/gajus/eslint-plugin-jsdoc

### LINKED ISSUE #225: [DRAFT] remove depricated file `bin/cyclonedx-bom`
fie `bin/cyclonedx-bom` is deprecated. 
file still exists for compatibility reasons. see #224 

a a developer i want this file removed, so all JavaScript files have a proper file extension `.js`.

----

if this _DRAFT_ is rejected, then remove the warning in the fie `bin/cyclonedx-bom`

### LINKED ISSUE #226: DRAFT: restructure project
:construction:  this ISSUE IS STILL A **DRAFT** :construction: 

----
based on current implementation  - 
restructure the project: 
* bin/
  * make-bom.js  - if it is desired, multi-purpose wrapper for npm/yarn
  * npm-bom.js
  * yarn-bom.js -- if this exists
* res/
  * spdx-licenses.json 
* src/
  * index.js  -- imports all public classes/functions and exports them right away. 
  * command/ 
    * options -- the options that all bins/commands have in common  
  * models/
    *  // the models 
  * buiders/  -- pull the logic out of the models so they become plain models
  * factories/   -- pull the logic out of the models so they become plain models
  * serialize/ -- serializers and normalizers 
  * spdx/
    * // SPDX specific implementation 
* tests/
  * // the tests 

----
in the ling run: rewrite the whole project. split out a _library_ - the models, the serializers/normalizers, core functionality.
keep the node/npm/yarn/... specifics in here.

the _library_ has the node and web browsers as a target. therefore it needs to be compatible to them.  Transpile to propriate target with webpack/babel/... is an option.

the node specifics dont need to support browser implementations of JavaScript.

motivation: 
* split the node-specifics from the general-purpose-implementations.
* have the core functionality in a browser-runnable language, so people can write UI for them.

### LINKED ISSUE #229: SBOM JSON result: add `$schema`
requires https://github.com/CycloneDX/specification/issues/106

----

the current JSON result follows an existing  schema, described in https://github.com/CycloneDX/specification/tree/master/schema

**feature request:**  add the used schema as a property `$schema` of the resulting json. 
the value must be the `$id` of the schema used. 

| spec |schema-id | 
| --- | --- |
| 1.2 | `http://cyclonedx.org/schema/bom-1.2a.schema.json` | 
| 1.3 | `http://cyclonedx.org/schema/bom-1.3.schema.json` | 

**example:** 
```json
{
  "$schema": "http://cyclonedx.org/schema/bom-1.3.schema.json",
  "bomFormat": "CycloneDX",
  "specVersion": "1.3",
  "serialNumber": "urn:uuid:3e671687-395b-41f5-a30f-a58921a69b79",
  "version": 1,
  "components": [
    {
      "type": "library",
      "name": "acme-library",
      "version": "1.0.0"
    }
  ]
}
```

### LINKED ISSUE #233: use private properties with `#`
since node12/es6 classes may have private properties - starting with `#`
see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields

currently `_` is used to mark properties as internal.

goal: use `#` 

----

this is considered a non-breaking "style" change, because the current privates were never intended to be used downstream.
If this breaks something for a user downstream, then they ran the code on their own risks already.

### LINKED ISSUE #242: Support patch-package for component pedigree information
I think it would be great to add support for component pedigree information from patch-package https://github.com/ds300/patch-package

### LINKED ISSUE #249: spec 1.4: `component.version` optional
from spec 1.4 on the Component's `version` is no longer required.
therefore it may be undefined and can be omitted when normalizing to JSON or to XML.
an empty version string is still valid.

feature: 
make `version` optional in setters.
make `version` default to `undefined`

### LINKED ISSUE #255: FF in license file throws error
After calling
`npx @cyclonedx/bom -l`
I got a 
`throw new Error("Invalid character in string: ${str} at index ${res.index}");`

It happens only with the parameter -l for "Include full license text"

Add the mentioned position is a form feed (0x0c) in the text. I guess, that the form feed is not correctly handled/masked/.. for the xml output.

The simplified used package.json is
`{
  "name": "bom_formfeed_in_license_file_issue",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "author": "CompartMSL",
  "license": "ISC",
  "dependencies": {
    "mariadb": "^2.5.5"
  }
}`

Stdout/stderr in more details
```
            throw new Error(`Invalid character in string: ${str} at index ${res.index}`);
            ^

Error: Invalid character in string:                  GNU LESSER GENERAL PUBLIC LICENSE
                       Version 2.1, February 1999

 Copyright (C) 1991, 1999 Free Software Foundation, Inc.
[..]
That's all there is to it!
 at index undefined
    at XMLStringifier.assertLegalChar (C:\Users\msl\AppData\Roaming\npm-cache\_npx\16684\node_modules\@cyclonedx\bom\node_modules\xmlbuilder\lib\XMLStringifier.js:210:19)
    at XMLStringifier.cdata (C:\Users\msl\AppData\Roaming\npm-cache\_npx\16684\node_modules\@cyclonedx\bom\node_modules\xmlbuilder\lib\XMLStringifier.js:62:21)
    at new XMLCData (C:\Users\msl\AppData\Roaming\npm-cache\_npx\16684\node_modules\@cyclonedx\bom\node_modules\xmlbuilder\lib\XMLCData.js:21:35)
    at XMLElement.cdata (C:\Users\msl\AppData\Roaming\npm-cache\_npx\16684\node_modules\@cyclonedx\bom\node_modules\xmlbuilder\lib\XMLNode.js:318:17)
    at XMLElement.element (C:\Users\msl\AppData\Roaming\npm-cache\_npx\16684\node_modules\@cyclonedx\bom\node_modules\xmlbuilder\lib\XMLNode.js:175:30)
    at XMLElement.element (C:\Users\msl\AppData\Roaming\npm-cache\_npx\16684\node_modules\@cyclonedx\bom\node_modules\xmlbuilder\lib\XMLNode.js:163:32)
    at XMLElement.element (C:\Users\msl\AppData\Roaming\npm-cache\_npx\16684\node_modules\@cyclonedx\bom\node_modules\xmlbuilder\lib\XMLNode.js:158:27)
    at XMLElement.element (C:\Users\msl\AppData\Roaming\npm-cache\_npx\16684\node_modules\@cyclonedx\bom\node_modules\xmlbuilder\lib\XMLNode.js:158:27)
    at XMLElement.element (C:\Users\msl\AppData\Roaming\npm-cache\_npx\16684\node_modules\@cyclonedx\bom\node_modules\xmlbuilder\lib\XMLNode.js:115:30)
    at XMLElement.element (C:\Users\msl\AppData\Roaming\npm-cache\_npx\16684\node_modules\@cyclonedx\bom\node_modules\xmlbuilder\lib\XMLNode.js:158:27)```

### LINKED ISSUE #256: Invalid or unexpected token in 3.4.1
New version seems to be broken:
> npx @cyclonedx/bom my\path --include-license-text --output "my\path\bom.xml" --type application
npx: installed 47 in 4.703s
Invalid or unexpected token

After forcing old version it works fine:
> npx @cyclonedx/bom@3.3.1 my\path --include-license-text --output "my\path\bom.xml" --type application

Unfortunately, there is no more output that could help track this down :/

version 3.4.0 also has the same issue.

### LINKED ISSUE #273: bump integration tests: use non-vulnerable components
there are integration tests in [`tests/integration/*/package.json`](https://github.com/CycloneDX/cyclonedx-node-module/tree/master/tests/integration) that may have npm compo ents that are vulnerable.
The code in these packages is never actually run. 

SecurityScanners often find new or the same issues in there, and mark _cyclonedx-node-module_ to have vulnerabilities,
unless someone marks them as "invalid, code is not executed". 
This is a manual job, each time. 

feature: 
* exclude `/tests/integration/*/package.json` from scanning for updates
* exclude `/tests/integration/*/package.json` from scanning for scurity-issues
* use dependencies that are more controlled, than the current  arbitrary set of things.

### LINKED ISSUE #294: [YARN] support yarn2/yarn3
yarn1 support is there,

yarn2 support is missing. 
* see https://github.com/CycloneDX/cyclonedx-node-module/issues/238#issuecomment-1109580824
* see https://github.com/CycloneDX/cyclonedx-node-module/pull/293

:exclamation: the yarn support got a dedicated project in the making: https://github.com/CycloneDX/cyclonedx-node-yarn

### LINKED ISSUE #298: use CDX-JS lib for data models, serialization and everythig.
use https://github.com/CycloneDX/cyclonedx-javascript-library/ / https://www.npmjs.com/package/%40cyclonedx/cyclonedx-library
instead of defining own models, normalizers, etc ... 

this is seen as a braking change, as own exported API is removed.

### LINKED ISSUE #306: split code in library and application part
Parts of the code can be used as a library by other tools downstream.  This already happens in https://github.com/CycloneDX/cyclonedx-webpack-plugin/ 
Other parts are application-specific.

split thosse parts, 
have the library-entrypoint linked as the package's `main` 
and the application entry point as the package's `bin`.

### LINKED ISSUE #337: [PSA] ALTERNATIVES :exclamation: :mega:
this project is not properly maintained, since all efforts go to individual ecosystem implementations. 
If you encounter any issues with this project, feel free to test or support the following alternatives: 

| ecosystem | CDX implementation status | link to the project |
|:---:|:---:|:---|
|  **NPM** |   stable  |  <https://www.npmjs.com/package/@cyclonedx/cyclonedx-npm> |
| **YARN** |   in-dev | <https://github.com/CycloneDX/cyclonedx-node-yarn> |
|  **PNPM** |   in-dev |   <https://github.com/CycloneDX/cyclonedx-node-pnpm> |
| **PARCEL** |  in planning | |

if you need a **library** to work with CycloneDX, then see 
<https://github.com/CycloneDX/cyclonedx-javascript-library>

### PR DESCRIPTION
**Pull request by jkowalleck**
path to go: have this package be meta-package for the following: 

* NPM: <https://www.npmjs.com/package/@cyclonedx/cyclonedx-npm>
* YARN: to be announced - probably https://github.com/CycloneDX/cyclonedx-node-yarn
* PNPM:  to be announced - probably https://github.com/CycloneDX/cyclonedx-node-pnpm
* PARCEL:   to be announced

each should be using https://github.com/CycloneDX/cyclonedx-javascript-library/ 
and be implemented in the way the ecosystems requires it to be.

Responsibility of the project: it can be installed nuder all circumstances.
and its "dependencies" are installed, if possible.

----

this feature actively
fixes #306 
closes #337

this PR drops features, and therefore 
closes #86 
closes #113
closes #117
closes #180
closes #182
closes #198 
fixes #215
closes #219
closes #220
fixes #225
closes #231
closes #232
closes #242
closes #249
closes #255
closes #256
closes #257
closes #272
closes #273
closes #293
closes #294
closes #310
closes #315 
closes #335
closes #311

this PR contradicts, and therefore
closes #226
closes #229
closes #233
closes #298

### CODE REVIEW

**Comment by weyert** [comment]
@jkowalleck Does this mean you are planning to add support for PNPM?

**Comment by jkowalleck** [comment]
@weyert i am planning to divide this project in multiple independent parts that are dedicated to the specific ecosystems.
Eventually there will be support for `pnpm`.

**Comment by DrMueller** [comment]
@jkowalleck Hello Jan, quick question: Will Version 4 support the schema version 1.4 as well? As I need to use schema version 1.4, do you know when it will be merged (if it actually does support it 😃 )

**Comment by jkowalleck** [comment]
@DrMueller

spec v1.4 support is already available as a library: https://www.npmjs.com/package/%40cyclonedx/cyclonedx-library
and for NPM projects a generator exists: https://github.com/CycloneDX/cyclonedx-node-npm

**Comment by DrMueller** [comment]
> @DrMueller
> 
> spec v1.4 support is already available as a library: https://www.npmjs.com/package/%40cyclonedx/cyclonedx-library and for NPM projects a generator exists: https://github.com/CycloneDX/cyclonedx-node-npm

Ah I see, thank you very much.

**Pull request merged**
