### PR TITLE
Extending license element

### PR DESCRIPTION
**Pull request by RaineInto**
Refers to the issue https://github.com/CycloneDX/specification/issues/15 of CycloneDX specification

Modification in createChild-function was needed so that the attribute(s) can be added in `<text>` element.

The license text is added (if found) as the value of `<text>` element without known side effects to the other parts of the code. License text input validation should be considered.

Additionally, I drafted a support for SPDX license expression syntax version 2.0 and custom license string mentioned [here](https://docs.npmjs.com/files/package.json#license). However, the solution is not complete. I'd be glad to hear your comments regarding this. UPDATE: There was already an issue on the expression syntax, which was considered in 1.1-DRAFT-3 of the specification. The [parser](https://www.npmjs.com/package/spdx-expression-parse) follows SPDX specification but does not accept custom licensing, which is in my interest, particularly, when the (license) filename is given.

### CODE REVIEW

**Comment by RaineInto** [comment]
@stevespringett Anything new on this? The last [commit](https://github.com/CycloneDX/cyclonedx-node-module/pull/10/commits/3b659060f6730fb6c7250d8ac1c3ae6221410e48) should be omitted, since it is not a full solution to the SPDX syntax issue, but other than that this should be fine.

**Comment by stevespringett** [comment]
Thanks for the PR @RaineInto. I will review this weekend.

**Comment by stevespringett** [comment]
Looks like a merge conflict, but I'll have to add optional support for schema 1.1 before merging this in, otherwise it will break existing schema 1.0 usage.

**Comment by RaineInto** [comment]
@stevespringett The merge conflict solved and a few modifications made, please review again.

Just to point out here, the conflict was due to https://github.com/CycloneDX/cyclonedx-node-module/pull/8, which is a (incomplete) workaround to comply with the deprecated [license style](https://docs.npmjs.com/files/package.json#license). I mentioned the problem already in https://github.com/CycloneDX/specification/issues/15#issuecomment-467438868 regarding to the `<url>` element and I think my point was misunderstood. "Deprecated style" does not refer to CycloneDX 1.0 and it should not matter whether a user selects output format v1.1 or v1.0. The question is that do we want to support the deprecated [license style](https://docs.npmjs.com/files/package.json#license) or not. Currently, CycloneDX does not fully support neither style. As far as I know, the CycloneDX specification (1.0 or 1.1) does not editorialise this in any way. Naturally, the best would be to have support for all/both styles, but obviously this isn't trivial to implement.

Anyhow, I suggest that partial (pull request) solutions or workarounds are not accepted,
since they are most likely going to introduce more issues and confusion in the future. For example,
```node
if (spdxLicenses.some(v => { return l === v; })) {
    return { id : l };
} else {
    return { name : l };
}
```
does not work correctly for https://github.com/CycloneDX/cyclonedx-node-module/pull/8, since `l` is an object (`l.type` would be correct, but then it breaks with the current license style).

The license style support is not in my best interest (at least for now) and I don't have any bandwidth for this any longer, so I leave it to you. The only thing I cared was the `<text>` element, which comes with this pull request. If this breaks scheme 1.0 usage (I guess it does, since `<text>` element was not defined?), how and when are you planning to add this "optional support"? Perhaps a command-line flag, which enables the `<text>` element or something?

One more thing, referring to the lines 130 and 131 in [index.js](https://github.com/RaineInto/cyclonedx-node-module/blob/extending_license/index.js)
```node
['foo'].includes(typeof bar)
```
and
```node
typeof bar === "foo"
```
return the same thing, so I suggest that only one style is used. You make the decision.

**Comment by RaineInto** [comment]
@stevespringett Updates on this?

**Comment by stevespringett** [comment]
I'll likely have bandwidth next week to work on updating this module to support schema 1.1 and merge this in at that time. Again, thanks for the PR and for the clear comments above.

**Comment by RaineInto** [comment]
@stevespringett Can this be accepted ASAP, please.

**Comment by RaineInto** [comment]
Thanks! Looking forward to the updated scheme 1.1 :) @stevespringett

**Pull request merged**
